/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author Usuario
 */
public class dlgRestar extends javax.swing.JDialog {

    /**
     * Creates new form dlgRestar
     */
    public dlgRestar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(400, 300);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    dlgRestar() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDos = new javax.swing.JPanel();
        lblValor1 = new javax.swing.JLabel();
        txtValor1 = new javax.swing.JTextField();
        lblValor2 = new javax.swing.JLabel();
        txtValor2 = new javax.swing.JTextField();
        lblResultado = new javax.swing.JLabel();
        btnRestar1 = new javax.swing.JButton();
        btnSalir2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblValor1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblValor1.setText("1er Valor");
        pnlDos.add(lblValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        txtValor1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlDos.add(txtValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 190, -1));

        lblValor2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblValor2.setText("2do Valor");
        pnlDos.add(lblValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        txtValor2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlDos.add(txtValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 190, -1));

        lblResultado.setText("-------");
        pnlDos.add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 290, -1));

        btnRestar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRestar1.setText("Restar");
        btnRestar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestar1ActionPerformed(evt);
            }
        });
        pnlDos.add(btnRestar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 120, 50));

        btnSalir2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalir2.setText("Salir");
        btnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir2ActionPerformed(evt);
            }
        });
        pnlDos.add(btnSalir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 120, 50));

        getContentPane().add(pnlDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestar1ActionPerformed
        int numeroUno = Integer.parseInt(txtValor1.getText());
        int numeroDos = Integer.parseInt(txtValor2.getText());

        int total = numeroUno - numeroDos;

        lblResultado.setText(String.valueOf(total));
    }//GEN-LAST:event_btnRestar1ActionPerformed

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalir2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgRestar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgRestar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgRestar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgRestar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgRestar dialog = new dlgRestar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRestar1;
    private javax.swing.JButton btnSalir2;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblValor1;
    private javax.swing.JLabel lblValor2;
    private javax.swing.JPanel pnlDos;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    // End of variables declaration//GEN-END:variables
}
